### ISSUE TITLE
Failed Deployment of NSX-T Edge - Host did not have any virtual network defined

### ISSUE THREAD

**Issue by kabuataya** [lamw/vghetto-nsxt-automated-lab-deployment#1]
Hi, 
 I get the following error while trying to deploy the edge OVA

Import-VApp : 1/1/2018 11:26:43 PM	Import-VApp		Host did not have any virtual network defined.	
At C:\Users\kay\Desktop\Nested_Deployment.ps1:769 char:23
+ ... sxedge_vm = Import-VApp -Source $NSXTEdgeOVA -OvfConfiguration $nsxEd ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-VApp], OvfNoHostNic
    + FullyQualifiedErrorId : Client20_VappServiceImpl_ImportVApp_CreateImportSpecError,VMware.VimAutomation.ViCore.Cmdlets.Commands.ImportVApp

does this indicated any issues in the initial configuration. 

Note: never tried this on NSX-T 2.0, I am running the script on 2.1 version of NSX-T

**Comment by lamw** [comment]
I actually just deployed 2.1 w/o any issues, this looks to be environmental due to the error thrown ...

```
Host did not have any virtual network defined.
```

**Comment by kabuataya** [comment]
the issue was related to the fact that there is no existent standard switch with vm Network Port group. looks like the NSX Edge does require the host to have a standard switch even without any physical connectivity but with "VM Network" Port group Defined.
