### ISSUE TITLE
Creating vSAN disk Group fails on reservation - Failed to reserve disk

### ISSUE THREAD

**Issue by kabuataya** [lamw/vghetto-nsxt-automated-lab-deployment#2]
during deployment. it happens on 2 Nested ESXi Hosts although fake scsi reservation is set during the script execution. 

[01-02-2018_12:25:48] Adding ESXi host 192.168.1.172 to Cluster ...
[01-02-2018_12:25:55] Adding ESXi host 192.168.1.173 to Cluster ...
[01-02-2018_12:26:02] Enabling VSAN & disabling VSAN Health Check ...
[01-02-2018_12:26:30] Querying ESXi host disks to create VSAN Diskgroups ...
[01-02-2018_12:26:30] Creating VSAN DiskGroup for 192.168.1.171 ...
**New-VsanDiskGroup : 1/2/2018 12:27:21 AM	New-VsanDiskGroup		Server task failed: A general system error occurred: Failed to reserve disk naa.6000c29214e6756d49a926a32ec4d244 with exception: Failed to reserve disk** 
naa.6000c29214e6756d49a926a32ec4d244 with exception: Reserve failed with error code: -1	
At C:\Users\kay\Desktop\Nested_Deployment.ps1:898 char:13
+             New-VsanDiskGroup -Server $vc -VMHost $vmhost -SsdCanonic ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-VsanDiskGroup], VimException
    + FullyQualifiedErrorId : Storage_Impl_TaskResultConverter_TaskNotSucceeded,VMware.VimAutomation.Storage.Commands.Cmdlets.Vsan.NewVsanDiskGroup

**Comment by lamw** [comment]
This seems to look like fake SCSI reservation issue, can you manually confirm the setting was applied? If its set properly, you shouldn't see any issues related to disk reserve

**Comment by kabuataya** [comment]
even though the command to create a fake scsi reservation on vSAN was part of the script. it seems that it was not taking effect. i have done the settings manually and it worked perfectly after that.
