### ISSUE TITLE
Processing Certificate thumbprint failed - ObjectNotFound

### ISSUE THREAD

**Issue by kabuataya** [lamw/vghetto-nsxt-automated-lab-deployment#3]
[01-02-2018_12:28:46] Clearing default VSAN Health Check Alarms, not applicable in Nested ESXi env ...
[01-02-2018_12:28:46] Disconnecting from new VCSA ...
[01-02-2018_12:28:56] Successfully logged into NSX Manager nsxt-mgr.kay.local  ...
[01-02-2018_12:28:56] Connecting back to Management vCenter Server vcenter.kay.local ...
[01-02-2018_12:28:57] Retrieving NSX Manager Thumbprint ...
[01-02-2018_12:28:58] Configuring NSX Controller nsxt-ctr1 as control-cluster master ...
[01-02-2018_12:28:58] Sending admin username ...
[01-02-2018_12:29:00] Sending admin password ...
[01-02-2018_12:29:05] Sending join management plane command ...
[01-02-2018_12:29:36] Sending shared secret command ...
[01-02-2018_12:29:41] Sending control cluster init command ...
[01-02-2018_12:30:06] Configuring additional NSX Controller nsxt-ctr2 ...
[01-02-2018_12:30:06] Sending admin username ...
[01-02-2018_12:30:08] Sending admin password ...
[01-02-2018_12:30:13] Sending join management plane command ...
[01-02-2018_12:30:43] Sending shared secret command ...
[01-02-2018_12:30:48] Sending exit command ...
[01-02-2018_12:30:59] Sending root username ...
[01-02-2018_12:31:01] Sending root password ...
[01-02-2018_12:31:11] Sending get control cluster cert ...
[01-02-2018_12:31:36] Processing certificate thumbprint ...
Copy-VMGuestFile : 1/2/2018 12:31:36 AM	Copy-VMGuestFile		The underlying connection was closed: An unexpected error occurred on a receive.	
At C:\Users\kay\Desktop\Nested_Deployment.ps1:1035 char:17
+ ...             Copy-VMGuestFile -vm (Get-VM -Name $nsxCtrName) -GuestToL ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-VMGuestFile], ViError
    + FullyQualifiedErrorId : Client20_VmGuestServiceImpl_DownloadFileFromGuest_DownloadError,VMware.VimAutomation.ViCore.Cmdlets.Commands.CopyVMGuestFile
 
Get-Content : Cannot find path 'C:\Users\kay\AppData\Local\Temp\controller-thumbprint' because it does not exist.
At C:\Users\kay\Desktop\Nested_Deployment.ps1:1036 char:48
+ ... Thumbprint = Get-Content -Path $ENV:TMP\controller-thumbprint | ? {$_ ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\kay\Ap...ller-thumbprint:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

**Comment by lamw** [comment]
Again, it looks like you've probably got some environmental issues that you should investigate before re-running the script. The underlying connection seems to be related ...

**Comment by kabuataya** [comment]
Hi William,
 I troubleshooted all other issues related to the deployment o the edge. but I am still struggling with this one. same as the above.


Copy-VMGuestFile : 1/2/2018 9:39:56 PM	Copy-VMGuestFile		The underlying connection was closed: An unexpected error occurred on a receive.	
At C:\Users\kay\Desktop\Nested_Deployment1.ps1:1043 char:17
+ ...             Copy-VMGuestFile -vm (Get-VM -Name $nsxCtrName) -GuestToL ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-VMGuestFile], ViError
    + FullyQualifiedErrorId : Client20_VmGuestServiceImpl_DownloadFileFromGuest_DownloadError,VMware.VimAutomation.ViCore.Cmdlets.Commands.CopyVMGuestFile
 
Get-Content : Cannot find path 'C:\Users\kay\AppData\Local\Temp\controller-thumbprint' because it does not exist.
At C:\Users\kay\Desktop\Nested_Deployment1.ps1:1044 char:48
+ ... Thumbprint = Get-Content -Path $ENV:TMP\controller-thumbprint | ? {$_ ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\kay\Ap...ller-thumbprint:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
 

I dont understand what this piece of code trying to execute. I ran the ISE as an administrator so there shouldn't be any issues in accessing directories in the system. 


the code base having this issue is

 ```
 # Retrieve Control Cluster Thumbprint by running nsxcli in the shell and
                # storing the thumbprint to a file which we will download later
                if($debug) { My-Logger "Sending get control cluster cert ..." }
                $ctrClusterThumbprintCmd = "nsxcli -c `"get control-cluster certificate thumbprint`" > /tmp/controller-thumbprint"
                Set-VMKeystrokes -VMName $nsxCtrName -StringInput $ctrClusterThumbprintCmd -ReturnCarriage $true
                Start-Sleep 25

                if($debug) { My-Logger "Processing certificate thumbprint ..." }
                Copy-VMGuestFile -vm (Get-VM -Name $nsxCtrName) -GuestToLocal -GuestUser "root" -GuestPassword $NSXRootPassword -Source /tmp/controller-thumbprint -Destination $ENV:TMP\controller-thumbprint | Out-Null
                $nsxControllerCertThumbprint = Get-Content -Path $ENV:TMP\controller-thumbprint | ? {$_.trim() -ne "" }

                # Exit from shell
                if($debug) { My-Logger "Sending exit command ..." }
                Set-VMKeystrokes -VMName $nsxCtrName -StringInput "exit" -ReturnCarriage $true
                Start-Sleep 10

```

**Comment by kabuataya** [comment]
I am trying to find the resolution for the problem. the best effort I was able to find that there is some sort of permission issue that takes place when powershell execute a command to copy the certificate thumbprint into the folder in the powershell server. 

I tried everything from setting static directories instead of the temp folder but still the issue persist with the following. i created the folder contoller-thumbprint in advance and I set all the permissions needed but still same issue persisting with the following error code. 
Copy-VMGuestFile : 1/4/2018 1:43:16 AM    Copy-VMGuestFile        The underlying connection was closed: An unexpected error occurred on a receive.    
At C:\Users\Administrator\Desktop\NestedNSXT.ps1:1043 char:17
+                 Copy-VMGuestFile -vm (Get-VM -Name $nsxCtrName) -GuestToLocal -G ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-VMGuestFile], ViError
    + FullyQualifiedErrorId : Client20_VmGuestServiceImpl_DownloadFileFromGuest_DownloadError,VMware.VimAutomation.ViCore.Cmdlets.Commands.CopyVMGuestFile
 
Get-Content : Access to the path 'C:\controller-thumbprint' is denied.
At C:\Users\Administrator\Desktop\NestedNSXT.ps1:1044 char:48
+                 $nsxControllerCertThumbprint = Get-Content -Path C:\controller-t ...
+                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\controller-thumbprint:String) [Get-Content], UnauthorizedAccessException
    + FullyQualifiedErrorId : GetContentReaderUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetContentCommand


are there any specific permission requirement that I have to do to allow access to these folders. I ran the ISE and the powershell both as administrator but still the issue keeps coming even after multiple tries and multiple options.

**Comment by lamw** [comment]
I'd recommend you try to setup PowerCLI on another system that you've deployed to rule out the possibility of the current host having issues and ensure it has full network access to both VC/ESXi host you're deploying to. You may also want to manually perform copy file from another guest from your current setup to see if you're seeing same issue.

**Comment by kabuataya** [comment]
the issue seem to happen randomly on different controller every time I run the script. I tried running the script on different machines and different operating systems but still it seems to continue to happen. 


[01-06-2018_08:34:23] Processing certificate thumbprint ...
Copy-VMGuestFile : The destination 'C:\Temp\controller-thumbprint' is invalid or does not exist. Specify 'Force' parameter to create the missing directories in the path.
At C:\Users\Administrator\Desktop\nested.ps1:1043 char:17
+ ...             Copy-VMGuestFile -vm (Get-VM -Name $nsxCtrName) -GuestToL ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-VMGuestFile], VimException
    + FullyQualifiedErrorId : VMware.VimAutomation.Sdk.Types.V1.ErrorHandling.VimException.VimException,VMware.VimAutomation.ViCore.Cmdlets.Commands.CopyVMGuestFile
 
Get-Content : Cannot find path 'C:\Temp\controller-thumbprint' because it does not exist.
At C:\Users\Administrator\Desktop\nested.ps1:1044 char:48
+ ... tThumbprint = Get-Content -Path C:\Temp\controller-thumbprint | ? {$_ ...
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Temp\controller-thumbprint:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
 
[01-06-2018_08:34:23] Sending exit command ...
[01-06-2018_08:34:33] Sending admin username ...
[01-06-2018_08:34:35] Sending admin password ...
[01-06-2018_08:34:40] Sending join control cluster command ...
[01-06-2018_08:35:10] Sending control cluster activate command ...
[01-06-2018_08:35:40] Sending final exit ...
[01-06-2018_08:35:40] Configuring additional NSX Controller nsxt-ctr3 ...
[01-06-2018_08:35:40] Sending admin username ...
[01-06-2018_08:35:42] Sending admin password ...
[01-06-2018_08:35:48] Sending join management plane command ...
[01-06-2018_08:36:18] Sending shared secret command ...
[01-06-2018_08:36:23] Sending exit command ...
[01-06-2018_08:36:33] Sending root username ...
[01-06-2018_08:36:35] Sending root password ...
[01-06-2018_08:36:45] Sending get control cluster cert ...
[01-06-2018_08:37:10] Processing certificate thumbprint ...
Copy-VMGuestFile : The destination 'C:\Temp\controller-thumbprint' is invalid or does not exist. Specify 'Force' parameter to create the missing directories in the path.
At C:\Users\Administrator\Desktop\nested.ps1:1043 char:17
+ ...             Copy-VMGuestFile -vm (Get-VM -Name $nsxCtrName) -GuestToL ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-VMGuestFile], VimException
    + FullyQualifiedErrorId : VMware.VimAutomation.Sdk.Types.V1.ErrorHandling.VimException.VimException,VMware.VimAutomation.ViCore.Cmdlets.Commands.CopyVMGuestFile
 
Get-Content : Cannot find path 'C:\Temp\controller-thumbprint' because it does not exist.
At C:\Users\Administrator\Desktop\nested.ps1:1044 char:48
+ ... tThumbprint = Get-Content -Path C:\Temp\controller-thumbprint | ? {$_ ...
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Temp\controller-thumbprint:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand


it is really weird how this is happening at my site and not at yours. I have just changed the command to create the file by force updating the command as follows. 


```
Copy-VMGuestFile -vm (Get-VM -Name $nsxCtrName) -GuestToLocal -GuestUser "root" -GuestPassword $NSXRootPassword -Source /tmp/controller-thumbprint -Destination C:\Temp\controller-thumbprint -**Force** | Out-Null
                $nsxControllerCertThumbprint = Get-Content -Path C:\Temp\controller-thumbprint | ? {$_.trim() -ne "" }
```

and it still has failed on the attempted in deploying second and third controllers with the same error. 

for some reason after the configuration of the first controller the file gets deleted and it is trying to read the same content but because the file doesn't exist it just comes back with the error. my understanding of the scrips is that it creates the file every time. 

this situation end up where the script doesn't complete execution and wait on the script as follows. 


[01-06-2018_09:26:51] Configuring NSX Edge nsxt-edge ...
[01-06-2018_09:26:51] Sending admin username ...
[01-06-2018_09:26:53] Sending admin password ...
[01-06-2018_09:26:58] Sending join management plane command ...
[01-06-2018_09:27:23] Sending final exit ...
[01-06-2018_09:27:23] Sending final exit to initial Controller ...
[01-06-2018_09:27:23] Disconnecting from NSX Manager ...
[01-06-2018_09:27:23] Disconnecting from Management vCenter ...
[01-06-2018_09:27:24] Successfully logged into NSX Manager nsxt-mgr.kay.local  ...
[01-06-2018_09:27:24] Verifying health of all NSX Manager/Controller Nodes ...
[01-06-2018_09:27:24] Check health status of Mgmt Node 192.168.1.175 ...
[01-06-2018_09:27:24] Checking health of Ctrl Node 192.168.1.176 ...
[01-06-2018_09:27:24] Checking health of Ctrl Node 192.168.1.178 ...
**[01-06-2018_09:27:24] 192.168.1.178 is not ready, sleeping 20 seconds ...
[01-06-2018_09:27:44] 192.168.1.178 is not ready, sleeping 20 seconds ...
[01-06-2018_09:28:04] 192.168.1.178 is not ready, sleeping 20 seconds ...**

**Comment by rbales79** [comment]
I have the same issue consistently, on separate fresh installs of windows server 2012 and server 2016., I can manually configure the additional controllers and the script will continue.
